[package]
name = "cetramed-polylux"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Andreas Kröpelin"]
license = "MIT"
description = "CeTraMed template for Polylux"
# repository = "https://github.com/polylux-typ/metropolis"
keywords = ["cetramed", "ukj", "jena", "polylux", "presentation", "slides", "slide", "talk", "lecture"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnail.png"
